build:
	javac -cp jaylib-5.5.0-2.jar *.java
run:
	java -cp jaylib-5.5.0-2.jar:. Program
run-mac:
	java -XstartOnFirstThread -cp jaylib-5.5.0-2.jar:. Program
run-win:
	java -cp jaylib-5.5.0-2.jar;. Program
